apiVersion: v1
appVersion: "1.2.2"
description: The Cloud-Native Ingress and Service Mesh for APIs and Microservices
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
name: apim
version: 0.1.2
