apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "{{ .Values.exporter.name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Values.exporter.name }}"
  replicas: {{ .Values.exporter.replicas }}
  template:
    metadata:
      labels:
        app: "{{ .Values.exporter.name }}"
    spec:
      containers:
      - name: "{{ .Values.exporter.name }}"
        image: "{{ .Values.exporter.image }}"
        env:
        - name: SERVICE_NAME
          value: "{{ template "kong.fullname" .}}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: kONG_ADMIN_PORT
          value: "{{ .Values.admin.servicePort }}"
        - name: PORT
          value: "{{ .Values.exporter.env.port }}"
        ports:
        - containerPort: {{ .Values.exporter.port }}
      serviceAccount: {{ .Values.exporter.name }}
